// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: web app was not re-registered in the new "Portativ" Firebase project.
  // If you need web support, add a Web app in Firebase console and replace this block.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0LSWKifd9Z9fUYQI8Mvf7Wfu1z9WAhs',
    appId: '1:1079410507859:web:e95a0ce16fbd2d38af46a6',
    messagingSenderId: '1079410507859',
    projectId: 'musical-theory-7be22',
    authDomain: 'musical-theory-7be22.firebaseapp.com',
    storageBucket: 'musical-theory-7be22.appspot.com',
    measurementId: 'G-GPNQNEKECP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClgdUQsXQijGZWTk1gX__5YxKyoTpaJdk',
    appId: '1:257631992316:android:4e4e603abe9df9c4bcda79',
    messagingSenderId: '257631992316',
    projectId: 'portativ-43e16',
    storageBucket: 'portativ-43e16.firebasestorage.app',
  );

  // TODO: apiKey below is still the OLD project's key. Download the fresh
  // GoogleService-Info.plist from Firebase console (Project settings > your
  // Portativ iOS app) and paste the real API_KEY value here before building for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zU32CNGYUun7RyEuc3g-azPjX9A9pD4',
    appId: '1:257631992316:ios:854bf492b57d5ee0bcda79',
    messagingSenderId: '257631992316',
    projectId: 'portativ-43e16',
    storageBucket: 'portativ-43e16.firebasestorage.app',
    iosBundleId: 'com.example.portativ',
  );

  // TODO: same as above - refresh apiKey from the downloaded GoogleService-Info.plist.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zU32CNGYUun7RyEuc3g-azPjX9A9pD4',
    appId: '1:257631992316:ios:854bf492b57d5ee0bcda79',
    messagingSenderId: '257631992316',
    projectId: 'portativ-43e16',
    storageBucket: 'portativ-43e16.firebasestorage.app',
    iosBundleId: 'com.example.portativ.RunnerTests',
  );
}
